// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CategoryReq struct {
	Id int64 `path:"id"`
}

type CategoryResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	ParentId    int64  `json:"parent_id"`
	Level       int    `json:"level"`
	Sort        int    `json:"sort"`
	Description string `json:"description,omitempty"`
	Status      int    `json:"status"`
}

type CreateCategoryReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	ParentId    int64  `json:"parent_id,optional"`
	Level       int    `json:"level,optional,default=1"`
	Sort        int    `json:"sort,optional,default=0"`
	Description string `json:"description,optional"`
}

type ListCategoryReq struct {
	Page     int `form:"page,optional,default=1"`
	PageSize int `form:"page_size,optional,default=10"`
}

type ListCategoryResp struct {
	List  []CategoryResp `json:"list"`
	Total int64          `json:"total"`
}
