// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	resource_catalog "idrm/api/internal/handler/resource_catalog"
	"idrm/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建类别
				Method:  http.MethodPost,
				Path:    "/categories",
				Handler: resource_catalog.CreateCategoryHandler(serverCtx),
			},
			{
				// 类别列表
				Method:  http.MethodGet,
				Path:    "/categories",
				Handler: resource_catalog.ListCategoryHandler(serverCtx),
			},
			{
				// 获取类别详情
				Method:  http.MethodGet,
				Path:    "/categories/:id",
				Handler: resource_catalog.GetCategoryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/catalog"),
	)
}
